---
- name: Add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Kubernetes Tools
  apt:
    name:
      - kubelet=1.28.2-00
      - kubeadm=1.28.2-00
      - kubectl=1.28.2-00
    state: present
    force_apt_get: yes
    allow_downgrade: yes

- name: Copy kubeadm-config.yaml to /etc/kubernetes/
  copy:
    src: files/kubeadm-config.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0644'
    
- name: Initialize the Kubernetes Cluster
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf

- name: Copy the kubernetes admin.conf to user's kube config
  command: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
